### ISSUE TITLE
Error after trying to transform text 

### ISSUE THREAD

**Issue by Nod2cs** [SuCicada/lain-voice-models#2]
Hello. First I want to say thank you for the work you do. 
I got an error after trying to transform text to speech on windows:
```
 warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
prober ffprobe
filepath <_io.BytesIO object at 0x000001C7B02352B0>
command ['ffprobe', '-of', 'json', '-v', 'info', '-show_format', '-show_streams', '-read_ahead_limit', '-1', 'cache:pipe:0']
Traceback (most recent call last):
  File "H:\laintts\venv\python\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\laintts\venv\python\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "H:\laintts\venv\python\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\laintts\venv\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\laintts\venv\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "H:\laintts\venv\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "H:\laintts\so-vits-svc-4.0\tools\lain_gradio.py", line 138, in tts_submit_func
    res = self.svc_infer.get_audio(
  File "H:\laintts\so-vits-svc-4.0\tools\..\tools\infer_base.py", line 57, in get_audio
    sampling_rate, audio = tts_utils.text_to_audio(text, tts_engine, language)
  File "H:\laintts\so-vits-svc-4.0\tools\..\tools\tts_utils.py", line 70, in text_to_audio
    sampling_rate, wav_bytes = text_to_wav(text, tts_engine, language)
  File "H:\laintts\so-vits-svc-4.0\tools\..\tools\tts_utils.py", line 66, in text_to_wav
    sampling_rate, wav_bytes = mp3_to_wav(mp3_bytes)
  File "H:\laintts\so-vits-svc-4.0\tools\..\tools\tts_utils.py", line 46, in mp3_to_wav
    mp3 = AudioSegment.from_file(io.BytesIO(mp3_bytes), format="mp3")
  File "H:\laintts\venv\python\lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "H:\laintts\venv\python\lib\site-packages\pydub\utils.py", line 280, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "H:\laintts\venv\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "H:\laintts\venv\python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2]
```
perhaps this is due to an error that occurs when running the bat file:

```
DEBUG:torchaudio._extension:Failed to initialize ffmpeg bindings
Traceback (most recent call last):
  File "H:\laintts\venv\python\lib\site-packages\torchaudio\_extension\utils.py", line 85, in _init_ffmpeg
    _load_lib("libtorchaudio_ffmpeg")
  File "H:\laintts\venv\python\lib\site-packages\torchaudio\_extension\utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "H:\laintts\venv\python\lib\site-packages\torch\_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "H:\laintts\venv\python\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'H:\laintts\venv\python\Lib\site-packages\torchaudio\lib\libtorchaudio_ffmpeg.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\laintts\venv\python\lib\site-packages\torchaudio\_extension\__init__.py", line 67, in <module>
    _init_ffmpeg()
  File "H:\laintts\venv\python\lib\site-packages\torchaudio\_extension\utils.py", line 87, in _init_ffmpeg
    raise ImportError("FFmpeg libraries are not found. Please install FFmpeg.") from err
ImportError: FFmpeg libraries are not found. Please install FFmpeg.
```
I unpacked the archives according to the instructions.

**Comment by Abybachir5** [comment]
получается у тебя .bat файл открыл вкладку в браузере? Или у тебя просто не трансформируется текст в голос?

**Comment by Nod2cs** [comment]
> получается у тебя .bat файл открыл вкладку в браузере? Или у тебя просто не трансформируется текст в голос?

Страница открывается. Не дает именно преобразовать текст в речь из-за неопределенного модуля так понимаю, хотя физически он там где его пытается определить скрипт.

**Comment by Abybachir5** [comment]
понятно, значит я както не так все распаковал и мне консоль не открывает ничего( она сразу сама закрывается и я не могу даже посмотреть url), но вроде я все делал по инструкции и не 1 раз

**Comment by SuCicada** [comment]
Thank you for your attention to my project.
I made a mistake sorry
now I have updated the code. https://github.com/SuCicada/lain-voice-models/commit/571c5107180b37d78870b2ff01582c7408e302e7

you just need re-download the [lain-voice.bat](https://raw.githubusercontent.com/SuCicada/lain-voice-models/master/lain-voice.bat) and replace the last one

please try it. If you still have questions, please contact me

**Comment by Nod2cs** [comment]
Thanks a lot! Everything works now.
